version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app_image
    container_name: app_container
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8050:8050"